version: "3.1"
services:
    db:
        build: ./db
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - TZ=Africa/Casablanca
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
        cap_add:
            - SYS_NICE 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: tibicha
            MYSQL_PASSWORD: tibicha
volumes:
    persistent: